#Using K Nearest Neighbor to calculate the KNN for the listings csv file of the project
#Here we are importing the libraries to create an KNN model for listings csv



In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import os

from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score

Reading the CSV file into the dataframe

In [2]:
df = pd.read_csv('/Users/ugoibe/Downloads/listings2.csv', low_memory=False)
df.head()

id                         listing_url       scrape_id last_scraped  \
0   2384   https://www.airbnb.com/rooms/2384  20190922191701   2019-09-22   
1   4505   https://www.airbnb.com/rooms/4505  20190922191701   2019-09-22   
2   7126   https://www.airbnb.com/rooms/7126  20190922191701   2019-09-22   
3   9811   https://www.airbnb.com/rooms/9811  20190922191701   2019-09-22   
4  10945  https://www.airbnb.com/rooms/10945  20190922191701   2019-09-22   

                                                name  \
0  Hyde Park Private Room - Pleasant Walk to UChi...   
1  One Great Apartment. 377 Great Reviews. 1 Bad ...   
2                Tiny Studio Apartment 94 Walk Score   
3                      Barbara's Hideaway - Old Town   
4                              The Biddle House (#1)   

                                             summary  \
0  You are invited to be the sole Airbnb guest in...   
1  We took the winter off, made things nicer arou...   
2   A very small studio in a wonderful neighborhood.   
3  One-bedroom hideaway tucked into Old Town step...   
4  Beautiful first floor apartment in Historic Ol...   

                                               space  \
0  The private bedroom has a queen size bed, beds...   
1  We travel a lot, we know what people need.  We...   
2  This is a very small  studio apartment with a ...   
3  This lovely one bedroom "hideaway" is located ...   
4  This 1st floor apartment has a queen size bed ...   

                                         description experiences_offered  \
0  You are invited to be the sole Airbnb guest in...                none   
1  We took the winter off, made things nicer arou...                none   
2  A very small studio in a wonderful neighborhoo...                none   
3  One-bedroom hideaway tucked into Old Town step...                none   
4  Beautiful first floor apartment in Historic Ol...                none   

                               neighborhood_overview  ... instant_bookable  \
0  My apartment is one block from beautiful Jacks...  ...                t   
1                                                NaN  ...                t   
2  Ukrainian Village was just named "Hottest Neig...  ...                f   
3  Chicago’s Old Town neighborhood is squeezed be...  ...                t   
4                                                NaN  ...                t   

  is_business_travel_ready          cancellation_policy  \
0                        f  strict_14_with_grace_period   
1                        f                     moderate   
2                        f                     moderate   
3                        f  strict_14_with_grace_period   
4                        f  strict_14_with_grace_period   

  require_guest_profile_picture require_guest_phone_verification  \
0                             f                                f   
1                             f                                f   
2                             f                                f   
3                             f                                f   
4                             f                                f   

   calculated_host_listings_count  \
0                               1   
1                               1   
2                               1   
3                              10   
4                              10   

   calculated_host_listings_count_entire_homes  \
0                                            0   
1                                            1   
2                                            1   
3                                           10   
4                                           10   

  calculated_host_listings_count_private_rooms  \
0                                            1   
1                                            0   
2                                            0   
3                                            0   
4                                            0   

   calculated_hos

Displaying the columsn in the dataframe so I can drop the ones I don't want

In [3]:
[col for col in df.columns]

['id',
 'listing_url',
 'scrape_id',
 'last_scraped',
 'name',
 'summary',
 'space',
 'description',
 'experiences_offered',
 'neighborhood_overview',
 'notes',
 'transit',
 'access',
 'interaction',
 'house_rules',
 'thumbnail_url',
 'medium_url',
 'picture_url',
 'xl_picture_url',
 'host_id',
 'host_url',
 'host_name',
 'host_since',
 'host_location',
 'host_about',
 'host_response_time',
 'host_response_rate',
 'host_acceptance_rate',
 'host_is_superhost',
 'host_thumbnail_url',
 'host_picture_url',
 'host_neighbourhood',
 'host_listings_count',
 'host_total_listings_count',
 'host_verifications',
 'host_has_profile_pic',
 'host_identity_verified',
 'street',
 'neighbourhood',
 'neighbourhood_cleansed',
 'neighbourhood_group_cleansed',
 'city',
 'state',
 'zipcode',
 'market',
 'smart_location',
 'country_code',
 'country',
 'latitude',
 'longitude',
 'is_location_exact',
 'property_type',
 'room_type',
 'accommodates',
 'bathrooms',
 'bedrooms',
 'beds',
 'bed_type',
 'amenities',


These are the columns that I am dropping but I am keeping the ones that I can calculate against

In [4]:
df.drop(['id',
 'listing_url',
 'scrape_id',
 'last_scraped',
 'name',
 'summary',
 'space',
 'description',
 'experiences_offered',
 'neighborhood_overview',
 'notes',
 'transit',
 'access',
 'interaction',
 'house_rules',
 'thumbnail_url',
 'medium_url',
 'picture_url',
 'xl_picture_url',
 'host_id',
 'host_url',
 'host_name',
 'host_since',
 'host_location',
 'host_about',
 'host_response_time',
 'host_response_rate',
 'host_acceptance_rate',
 'host_is_superhost',
 'host_thumbnail_url',
 'host_picture_url',
 'host_neighbourhood',
 'host_listings_count',
 'host_total_listings_count',
 'host_verifications',
 'host_has_profile_pic',
 'host_identity_verified',
 'street',
 'neighbourhood',
 'neighbourhood_cleansed',
 'neighbourhood_group_cleansed',
 'city',
 'state',
 'market',
 'smart_location',
 'country_code',
 'country',
 'is_location_exact',
 'property_type',
 'room_type',
 'bed_type',
 'amenities',
 'weekly_price',
 'monthly_price',
 'security_deposit',
 'cleaning_fee',
 'guests_included',
 'extra_people',
 'minimum_minimum_nights',
 'maximum_minimum_nights',
 'minimum_maximum_nights',
 'maximum_maximum_nights',
 'minimum_nights_avg_ntm',
 'maximum_nights_avg_ntm',
 'calendar_updated',
 'has_availability',
 'availability_30',
 'availability_60',
 'availability_90',
 'availability_365',
 'calendar_last_scraped',
 'number_of_reviews',
 'number_of_reviews_ltm',
 'first_review',
 'last_review',
 'review_scores_rating',
 'review_scores_accuracy',
 'review_scores_cleanliness',
 'review_scores_checkin',
 'review_scores_communication',
 'review_scores_location',
 'review_scores_value',
 'requires_license',
 'license',
 'jurisdiction_names',
 'instant_bookable',
 'is_business_travel_ready',
 'cancellation_policy',
 'require_guest_profile_picture',
 'require_guest_phone_verification',
 'calculated_host_listings_count',
 'calculated_host_listings_count_entire_homes',
 'calculated_host_listings_count_private_rooms',
 'calculated_host_listings_count_shared_rooms',
 'reviews_per_month', 'square_feet', 'zipcode'],1, inplace=True)

I am reassigning the dataframe into a new variable since I redimensioned the size sort to speak.

In [5]:
# new_data = df.dropna(axis = 0, how ='any') 
new_data = df
new_data

latitude  longitude  accommodates  bathrooms  bedrooms  beds      price  \
0     41.78886  -87.58671             1        1.0       1.0   1.0     $50.00   
1     41.85495  -87.69696             7        1.0       3.0   4.0    $117.00   
2     41.90289  -87.68182             2        1.0       1.0   1.0     $80.00   
3     41.91769  -87.63788             4        1.0       1.0   0.0    $150.00   
4     41.91183  -87.64000             4        1.0       2.0   2.0    $215.00   
5     41.92335  -87.64951             2        1.0       1.0   1.0    $289.00   
6     41.89617  -87.66041             4        2.0       2.0   2.0     $99.00   
7     41.91423  -87.63846             7        1.0       2.0   4.0    $145.00   
8     41.92083  -87.68010             6        2.0       3.0   3.0    $190.00   
9     41.97385  -87.66539             2        1.5       1.0   1.0     $77.00   
10    41.89377  -87.63465             2        1.0       1.0   1.0     $75.00   
11    41.91331  -87.63964             4        1.0       1.0   1.0     $75.00   
12    41.91287  -87.63979             3        1.0       1.0   2.0     $65.00   
13    41.91264  -87.63979             6        2.0       2.0   2.0    $155.00   
14    41.89687  -87.67989             2        1.0       1.0   1.0     $59.00   
15    41.96792  -87.65757             6        2.5       1.0   4.0    $180.00   
16    41.89693  -87.68033             2        1.0       1.0   1.0     $55.00   
17    41.96930  -87.65621             2        1.0       1.0   1.0     $99.00   
18    41.96804  -87.65123             1        1.0       1.0   1.0     $48.00   
19    41.93361  -87.71977             2        1.0       1.0   1.0     $80.00   
20    41.89243  -87.68078             3        1.0       2.0   2.0    $100.00   
21    41.94079  -87.65763             8        2.0       3.0   4.0    $225.00   
22    41.94364  -87.68155             8        2.0       3.0   4.0    $275.00   
23    41.91351  -87.63929            10        2.0       4.0   5.0    $475.00   
24    41.94274  -87.67321             4        1.0       2.0   2.0    $198.00   
25    41.94274  -87.67378             3        1.0       1.0   1.0    $125.00   
26    41.94221  -87.67327             8        2.0       3.0   3.0    $280.00   
27    41.89753  -87.67315             3        1.0       2.0   2.0     $75.00   
28    41.96012  -87.72158             4        1.0       1.0   1.0     $67.00   
29    41.94325  -87.75403             2        1.0       1.0   1.0     $85.00   
...        ...        ...           ...        ...       ...   ...        ...   
8822  41.84005  -87.64923             1        1.0       1.0   1.0     $25.00   
8823  41.81366  -87.69872             1        1.0       1.0   1.0     $21.00   
8824  41.96874  -87.71736             2        1.0       1.0   1.0     $19.00   
8825  41.74980  -87.61826             4        1.0       2.0   3.0     $65.00   
8826  41.93411  -87.72202             2        1.0       1.0   1.0     $49.00   
8827  41.89735  -87.62962             1        1.0       1.0   1.0     $59.00   
8828  41.87187  -87.63200             2        1.0       1.0   1.0     $80.00   
8829  41.90566  -87.62891             2        1.0       0.0   1.0    $109.00   
8830  41.88604  -87.62480             4        2.0       2.0   2.0    $167.00   
8831  41.88515  -87.62536             2        1.0       1.0   1.0    $124.00   
8832  41.93611  -87.70898             2        1.0       1.0   1.0     $99.00   
8833  41.83946  -87.66023             4        1.5       2.0   2.0     $63.00   
8834  41.88436  -87.70226             2        1.0       1.0   1.0     $65.00   
8835  41.94388  -87.73178             4        1.0       1.0   3.0     $73.00   
8836  41.83095  -87.62143             6        1.0       2.0   2.0     $99.00   
8837  41.85670  -87.63294             2        1.0       1.0   1.0     $50.00   
8838  41.88434  -87.64387             2        1.0       0.0   1.0    $113.00   
8839  41.93386  -87.65996            

Again this is for me but I want to display the columsn that is in the new dataframe and rearrange
the columns so I can place price at the end.  

In [6]:
[col for col in new_data.columns]

['latitude',
 'longitude',
 'accommodates',
 'bathrooms',
 'bedrooms',
 'beds',
 'price',
 'minimum_nights',
 'maximum_nights']

This is where I rearrange the columns 

In [7]:
col_rearrange = ['latitude',
 'longitude','accommodates',
 'bathrooms','bedrooms',
 'beds', 'minimum_nights',
 'maximum_nights','price']

new_data = new_data.reindex(columns=col_rearrange)

I want to display the dataframe with the rearranged columns to see if I have done it correctly.

In [8]:
new_data

latitude  longitude  accommodates  bathrooms  bedrooms  beds  \
0     41.78886  -87.58671             1        1.0       1.0   1.0   
1     41.85495  -87.69696             7        1.0       3.0   4.0   
2     41.90289  -87.68182             2        1.0       1.0   1.0   
3     41.91769  -87.63788             4        1.0       1.0   0.0   
4     41.91183  -87.64000             4        1.0       2.0   2.0   
5     41.92335  -87.64951             2        1.0       1.0   1.0   
6     41.89617  -87.66041             4        2.0       2.0   2.0   
7     41.91423  -87.63846             7        1.0       2.0   4.0   
8     41.92083  -87.68010             6        2.0       3.0   3.0   
9     41.97385  -87.66539             2        1.5       1.0   1.0   
10    41.89377  -87.63465             2        1.0       1.0   1.0   
11    41.91331  -87.63964             4        1.0       1.0   1.0   
12    41.91287  -87.63979             3        1.0       1.0   2.0   
13    41.91264  -87.63979             6        2.0       2.0   2.0   
14    41.89687  -87.67989             2        1.0       1.0   1.0   
15    41.96792  -87.65757             6        2.5       1.0   4.0   
16    41.89693  -87.68033             2        1.0       1.0   1.0   
17    41.96930  -87.65621             2        1.0       1.0   1.0   
18    41.96804  -87.65123             1        1.0       1.0   1.0   
19    41.93361  -87.71977             2        1.0       1.0   1.0   
20    41.89243  -87.68078             3        1.0       2.0   2.0   
21    41.94079  -87.65763             8        2.0       3.0   4.0   
22    41.94364  -87.68155             8        2.0       3.0   4.0   
23    41.91351  -87.63929            10        2.0       4.0   5.0   
24    41.94274  -87.67321             4        1.0       2.0   2.0   
25    41.94274  -87.67378             3        1.0       1.0   1.0   
26    41.94221  -87.67327             8        2.0       3.0   3.0   
27    41.89753  -87.67315             3        1.0       2.0   2.0   
28    41.96012  -87.72158             4        1.0       1.0   1.0   
29    41.94325  -87.75403             2        1.0       1.0   1.0   
...        ...        ...           ...        ...       ...   ...   
8822  41.84005  -87.64923             1        1.0       1.0   1.0   
8823  41.81366  -87.69872             1        1.0       1.0   1.0   
8824  41.96874  -87.71736             2        1.0       1.0   1.0   
8825  41.74980  -87.61826             4        1.0       2.0   3.0   
8826  41.93411  -87.72202             2        1.0       1.0   1.0   
8827  41.89735  -87.62962             1        1.0       1.0   1.0   
8828  41.87187  -87.63200             2        1.0       1.0   1.0   
8829  41.90566  -87.62891             2        1.0       0.0   1.0   
8830  41.88604  -87.62480             4        2.0       2.0   2.0   
8831  41.88515  -87.62536             2        1.0       1.0   1.0   
8832  41.93611  -87.70898             2        1.0       1.0   1.0   
8833  41.83946  -87.66023             4        1.5       2.0   2.0   
8834  41.88436  -87.70226             2        1.0       1.0   1.0   
8835  41.94388  -87.73178             4        1.0       1.0   3.0   
8836  41.83095  -87.62143             6        1.0       2.0   2.0   
8837  41.85670  -87.63294             2        1.0       1.0   1.0   
8838  41.88434  -87.64387             2        1.0       0.0   1.0   
8839  41.93386  -87.65996             8        1.0       3.0   3.0   
8840  41.88664  -87.62205             2        1.0       0.0   1.0   
8841  41.89609  -87.63251             4        1.0       1.0   2.0   
8842  41.87840  -87.71131             8        1.0       2.0   2.0   
8843  41.76052  -87.56331             2        1.0       1.0   2.0   
8844  41.65992  -87.65168             8        1.0       3.0   4.0   
8845  41.92618  -87.65649             6        1.5       3.0   3.0   
8846  41.90236  -87.70953             5        1.0       2.0   3.0   
8847  41.83454  

This is where I want to convert the column price to float and remove any extraneous symbols that might 
cause a compiling error when run.

In [9]:
new_data['price'] = new_data['price'].replace({'\$': '', ',': ''}, regex=True).astype(float)


Here I want to drop any null or zero values in all of the columns

In [10]:
zero_not_accepted = ['accommodates','bathrooms','bedrooms','beds','minimum_nights','maximum_nights','price']

for column in zero_not_accepted:
    new_data[column] = new_data[column].replace(0, np.NaN)
    mean = int(new_data[column].mean(skipna=True))
    new_data[column] = new_data[column].replace(np.NaN, mean)

Displaying the dataframe again so I see I dropped the $ symbols and any other symbols that might interfere with 
using KNN algorithm

In [11]:
new_data

latitude  longitude  accommodates  bathrooms  bedrooms  beds  \
0     41.78886  -87.58671             1        1.0       1.0   1.0   
1     41.85495  -87.69696             7        1.0       3.0   4.0   
2     41.90289  -87.68182             2        1.0       1.0   1.0   
3     41.91769  -87.63788             4        1.0       1.0   2.0   
4     41.91183  -87.64000             4        1.0       2.0   2.0   
5     41.92335  -87.64951             2        1.0       1.0   1.0   
6     41.89617  -87.66041             4        2.0       2.0   2.0   
7     41.91423  -87.63846             7        1.0       2.0   4.0   
8     41.92083  -87.68010             6        2.0       3.0   3.0   
9     41.97385  -87.66539             2        1.5       1.0   1.0   
10    41.89377  -87.63465             2        1.0       1.0   1.0   
11    41.91331  -87.63964             4        1.0       1.0   1.0   
12    41.91287  -87.63979             3        1.0       1.0   2.0   
13    41.91264  -87.63979             6        2.0       2.0   2.0   
14    41.89687  -87.67989             2        1.0       1.0   1.0   
15    41.96792  -87.65757             6        2.5       1.0   4.0   
16    41.89693  -87.68033             2        1.0       1.0   1.0   
17    41.96930  -87.65621             2        1.0       1.0   1.0   
18    41.96804  -87.65123             1        1.0       1.0   1.0   
19    41.93361  -87.71977             2        1.0       1.0   1.0   
20    41.89243  -87.68078             3        1.0       2.0   2.0   
21    41.94079  -87.65763             8        2.0       3.0   4.0   
22    41.94364  -87.68155             8        2.0       3.0   4.0   
23    41.91351  -87.63929            10        2.0       4.0   5.0   
24    41.94274  -87.67321             4        1.0       2.0   2.0   
25    41.94274  -87.67378             3        1.0       1.0   1.0   
26    41.94221  -87.67327             8        2.0       3.0   3.0   
27    41.89753  -87.67315             3        1.0       2.0   2.0   
28    41.96012  -87.72158             4        1.0       1.0   1.0   
29    41.94325  -87.75403             2        1.0       1.0   1.0   
...        ...        ...           ...        ...       ...   ...   
8822  41.84005  -87.64923             1        1.0       1.0   1.0   
8823  41.81366  -87.69872             1        1.0       1.0   1.0   
8824  41.96874  -87.71736             2        1.0       1.0   1.0   
8825  41.74980  -87.61826             4        1.0       2.0   3.0   
8826  41.93411  -87.72202             2        1.0       1.0   1.0   
8827  41.89735  -87.62962             1        1.0       1.0   1.0   
8828  41.87187  -87.63200             2        1.0       1.0   1.0   
8829  41.90566  -87.62891             2        1.0       1.0   1.0   
8830  41.88604  -87.62480             4        2.0       2.0   2.0   
8831  41.88515  -87.62536             2        1.0       1.0   1.0   
8832  41.93611  -87.70898             2        1.0       1.0   1.0   
8833  41.83946  -87.66023             4        1.5       2.0   2.0   
8834  41.88436  -87.70226             2        1.0       1.0   1.0   
8835  41.94388  -87.73178             4        1.0       1.0   3.0   
8836  41.83095  -87.62143             6        1.0       2.0   2.0   
8837  41.85670  -87.63294             2        1.0       1.0   1.0   
8838  41.88434  -87.64387             2        1.0       1.0   1.0   
8839  41.93386  -87.65996             8        1.0       3.0   3.0   
8840  41.88664  -87.62205             2        1.0       1.0   1.0   
8841  41.89609  -87.63251             4        1.0       1.0   2.0   
8842  41.87840  -87.71131             8        1.0       2.0   2.0   
8843  41.76052  -87.56331             2        1.0       1.0   2.0   
8844  41.65992  -87.65168             8        1.0       3.0   4.0   
8845  41.92618  -87.65649             6        1.5       3.0   3.0   
8846  41.90236  -87.70953             5        1.0       2.0   3.0   
8847  41.83454  

Here I am setting up my X and y variables from the dataframe.  My X values will consist of values from columns 0 to 5 and my y values will contains columns from 6 which is price.

In [12]:
X = new_data.iloc[:, 0:8]
y = new_data.iloc[:, 8]
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0, test_size=0.2)

From what I understand, this is putting the X values into the X_train variable to train it and the X values to transform into te X_test.

In [27]:
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

array([[ 1.90029495,  0.05895148, -0.1111607 , ..., -0.12639031,
        -0.26078515,  0.87459013],
       [-0.24749556,  0.78336635,  0.89841039, ...,  0.37753412,
        -0.19335336,  0.87459013],
       [ 0.83278138, -1.14387802, -0.1111607 , ..., -0.63031474,
        -0.26078515, -1.24288312],
       ...,
       [ 0.87053966,  0.06792782,  0.5618867 , ...,  0.88145856,
        -0.12592157, -1.09803347],
       [ 0.69078896, -1.51676002,  0.225363  , ..., -0.12639031,
        -0.26078515,  0.87459013],
       [ 0.73989245,  0.40781571,  0.5618867 , ..., -0.12639031,
        -0.19335336, -1.21620029]])

Here I will define the model I am using which is the K-NN model.

In [14]:
classifier = KNeighborsClassifier(n_neighbors=11, p=2, metric='euclidean')

In [15]:
# Fit model
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=11, p=2,
                     weights='uniform')

In [16]:
y_pred = classifier.predict(X_test)

In [17]:
y_pred

array([  80.,  400.,   49., ...,  200.,   70., 1000.])

In [18]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(f1_score(y_test, y_pred , average='micro'))

[[8 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 2 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
0.09034443817052512


In [19]:
print(accuracy_score(y_test, y_pred))

0.09034443817052512
